language: python
sudo: false
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF="djangorestframework==3.3.2"
   - WQDB="wq.db==0.8.4"
   - DRP="rest-pandas==0.4.0",
  matrix:
   - DJANGO="django==1.7.11"
   - DJANGO="django==1.8.8"
   - DJANGO="django==1.8.8" LINT=1
before_script:
 - createdb -Upostgres vera_test
 - psql -Upostgres vera_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $DRP
 - pip install $WQDB
 - pip install flake8
script:
 - ./runtests.sh
services:
 - redis-server
