language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.3.3"
   - WQDB="wq.db==1.0.0a1"
   - DRP="rest-pandas==0.4.0"
  matrix:
   - DJANGO="django==1.8.13"
   - DJANGO="django==1.9.7"
   - DJANGO="django==1.9.7" LINT=1
before_script:
 - createdb -Upostgres vera_test
 - psql -Upostgres vera_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $DRP
 - pip install $WQDB
 - pip install https://github.com/wq/django-natural-keys/archive/master.zip
 - pip install flake8
script:
 - ./runtests.sh
