language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.5.3"
   - WQDB="wq.db==1.0.0rc1"
   - DRP="rest-pandas==0.4.1"
  matrix:
   - DJANGO="django==1.8.16"
   - DJANGO="django==1.9.11"
   - DJANGO="django==1.10.3
   - DJANGO="django==1.10.3" LINT=1
before_script:
 - createdb -Upostgres vera_test
 - createdb -Upostgres vera_swap_test
 - psql -Upostgres vera_test -c "CREATE EXTENSION postgis;"
 - psql -Upostgres vera_swap_test -c "CREATE EXTENSION postgis;"
install:
 - pip install --upgrade pip
 - pip install $DJANGO $DRF $DRP matplotlib
 - pip install $WQDB
 - pip install https://github.com/wq/django-data-wizard/archive/master.zip
 - pip install flake8
script:
 - ./runtests.sh
services:
 - redis-server
