language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.4.6"
   - WQDB="wq.db==1.0.0b1"
   - DRP="rest-pandas==0.4.1"
  matrix:
   - DJANGO="django==1.8.14"
   - DJANGO="django==1.9.9"
   - DJANGO="django==1.10.1
   - DJANGO="django==1.10.1" LINT=1
before_script:
 - createdb -Upostgres vera_test
 - createdb -Upostgres vera_swap_test
 - psql -Upostgres vera_test -c "CREATE EXTENSION postgis;"
 - psql -Upostgres vera_swap_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $DRP
 - pip install $WQDB
 - pip install flake8
script:
 - ./runtests.sh
