language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.5.1"
   - WQDB="https://github.com/wq/wq.db/archive/master.zip"
   - NKEY="https://github.com/wq/django-natural-keys/archive/master.zip"
   - DRP="rest-pandas==0.4.1"
  matrix:
   - DJANGO="django==1.8.15"
   - DJANGO="django==1.9.10"
   - DJANGO="django==1.10.2
   - DJANGO="django==1.10.2" LINT=1
before_script:
 - createdb -Upostgres vera_test
 - createdb -Upostgres vera_swap_test
 - psql -Upostgres vera_test -c "CREATE EXTENSION postgis;"
 - psql -Upostgres vera_swap_test -c "CREATE EXTENSION postgis;"
install:
 - pip install --upgrade pip
 - pip install $DJANGO $DRF $DRP matplotlib
 - pip install $NKEY $WQDB
 - pip install flake8
script:
 - ./runtests.sh
